import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getAuthUser } from '@/lib/auth';

export async function GET() {
    try {
        const user = await getAuthUser();

        if (!user || user.usertype !== 'INSTITUTION') {
            return NextResponse.json({ error: 'Unauthorized - Admin access required' }, { status: 401 });
        }

        if (!user.institutionname) {
            return NextResponse.json({ error: 'Institution not found' }, { status: 400 });
        }

        // Fetch comprehensive admin statistics
        const institutionCerts = await prisma.certificate.findMany({
            where: {
                owner: {
                    institutionname: user.institutionname
                }
            },
            include: {
                owner: {
                    select: {
                        fullName: true,
                        username: true,
                        email: true
                    }
                }
            }
        });

        const totalCertificates = institutionCerts.length;
        const pending = institutionCerts.filter(c => c.status === 'PENDING').length;
        const approved = institutionCerts.filter(c => c.status === 'APPROVED').length;
        const rejected = institutionCerts.filter(c => c.status === 'REJECTED').length;
        const verified = institutionCerts.filter(c => c.status === 'VERIFIED').length;

        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const todayUploads = institutionCerts.filter(c => new Date(c.createdAt) >= today).length;

        const successRate = totalCertificates > 0
            ? Math.round((approved / (approved + rejected || 1)) * 100)
            : 0;

        // Generate CSV content with comprehensive report
        const csvContent = [
            '=== ADMIN DASHBOARD REPORT ===',
            `Institution: ${user.institutionname}`,
            `Generated: ${new Date().toLocaleString()}`,
            `Generated By: ${user.username}`,
            '',
            '=== SUMMARY STATISTICS ===',
            `Total Certificates,${totalCertificates}`,
            `Pending Review,${pending}`,
            `Approved,${approved}`,
            `Rejected,${rejected}`,
            `Verified,${verified}`,
            `Uploaded Today,${todayUploads}`,
            `Success Rate,${successRate}%`,
            '',
            '=== DETAILED CERTIFICATE LIST ===',
            'Certificate ID,Title,Student Name,Student Email,Status,Upload Date',
            ...institutionCerts.map(cert => [
                cert.id,
                cert.title || 'Untitled',
                cert.owner.fullName || cert.owner.username,
                cert.owner.email || 'N/A',
                cert.status,
                new Date(cert.createdAt).toLocaleDateString()
            ].map(cell => `"${cell}"`).join(','))
        ].join('\n');

        // Return CSV file
        return new NextResponse(csvContent, {
            status: 200,
            headers: {
                'Content-Type': 'text/csv',
                'Content-Disposition': `attachment; filename="admin-report-${user.institutionname.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.csv"`
            }
        });

    } catch (error: any) {
        console.error("Export Report error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
